### ISSUE TITLE
README commands don't make sense

### ISSUE THREAD

**Issue by juliamendelsohn** [williamleif/redditnetwork#1]
I was looking at the readme to try to run the package and notice that the commands in:  

> After you have (optionally) set-up the virtual environment, run pip setup.py install python -m spacy.en.download all python -m nltk.downloader stopwords 

Don't run. Could it be possible to separate the commands line by line so they are parsable? Also correct them if necessary. Thanks!

**Comment by williamleif** [comment]
Thanks! Do they make sense and work now?
